[package]
name = "beatbot-rs"
version = "0.1.0"
authors = ["David Phillips <david@daviddouglasphillips.com>"]

[dependencies]
beats = "0.1.3"
actix-web = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
env_logger = "0.5"
